// Mocks generated by Mockito 5.4.6 from annotations
// in gc_reminder/test/infrastructure/repositories/reminder/reminder_local_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:gc_reminder/core/networks/error_handler.dart' as _i6;
import 'package:gc_reminder/domain/dto/reminder/create_reminder_dto.dart'
    as _i9;
import 'package:gc_reminder/domain/dto/reminder/update_reminder_dto.dart'
    as _i10;
import 'package:gc_reminder/domain/models/reminder/reminder_filter_model.dart'
    as _i8;
import 'package:gc_reminder/domain/models/reminder/reminder_model.dart' as _i7;
import 'package:gc_reminder/domain/models/reminder/reminder_summary_model.dart'
    as _i11;
import 'package:gc_reminder/infrastructure/database/database.dart' as _i2;
import 'package:gc_reminder/infrastructure/datasource/reminder/reminder_local_datasource.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReminderLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderLocalDataSource extends _i1.Mock
    implements _i4.ReminderLocalDataSource {
  MockReminderLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#db)),
          )
          as _i2.AppDatabase);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReminderModel>>> getReminders({
    _i8.ReminderFilterModel? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReminders, [], {#filter: filter}),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.ReminderModel>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.ReminderModel>>(
                    this,
                    Invocation.method(#getReminders, [], {#filter: filter}),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReminderModel>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ReminderModel>> getReminder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReminder, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ReminderModel>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ReminderModel>(
                    this,
                    Invocation.method(#getReminder, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ReminderModel>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, int>> createReminder({
    required _i9.CreateReminderDTO? dto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReminder, [], {#dto: dto}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, int>>.value(
              _FakeEither_1<_i6.Failure, int>(
                this,
                Invocation.method(#createReminder, [], {#dto: dto}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, int>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> updateReminder(
    int? id, {
    required _i10.UpdateReminderDTO? dto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReminder, [id], {#dto: dto}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#updateReminder, [id], {#dto: dto}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteReminder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminder, [id]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#deleteReminder, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteReminders(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminders, [ids]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#deleteReminders, [ids]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i11.ReminderSummaryModel>> getSummary({
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, [], {#date: date}),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i11.ReminderSummaryModel>
                >.value(
                  _FakeEither_1<_i6.Failure, _i11.ReminderSummaryModel>(
                    this,
                    Invocation.method(#getSummary, [], {#date: date}),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i11.ReminderSummaryModel>>);
}
